name: Dhan Shield Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '45 3 * * 1-5'

jobs:
  monitor-portfolio:
    runs-on: ubuntu-latest
    timeout-minutes: 500 # 8 ghante tak script ko chalne dega
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Lib
        run: pip install dhanhq

      - name: Run Shield
        env:
          DHAN_CLIENT_ID: ${{ secrets.DHAN_CLIENT_ID }}
          DHAN_ACCESS_TOKEN: ${{ secrets.DHAN_ACCESS_TOKEN }}
        run: python dhan_shield.py
